# Generated by Django 5.0.3 on 2024-03-25 17:49

import Scan.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Upload', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.FileField(upload_to='Scan/image/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'csv']), Scan.models.validate_file_extension])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published', models.BooleanField(default=False)),
                ('upload', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Upload.upload')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
