# Generated by Django 5.0.3 on 2024-03-25 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='details',
            field=models.TextField(max_length=5),
        ),
    ]
